# silence mac zsh warning
export BASH_SILENCE_DEPRECATION_WARNING=1

# default PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# set editor
export EDITOR='nvim'
set -o vi

# brew install
eval "$(/opt/homebrew/bin/brew shellenv)"

# llvm
export PATH="$(brew --prefix llvm)/bin:${PATH}"

# node
export PATH="$HOME/.nodenv/shims:$PATH"
eval "$(nodenv init - bash)"

# ruby
export PATH="$HOME/.rbenv/shims:$PATH"
eval "$(rbenv init -)"

#python
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# go
export GOPATH="/Users/drujensen/.go"
export PATH="$HOME/.goenv/shims:$GOPATH/bin:$PATH"
eval "$(goenv init -)"

# swift
export SWIFTENV_ROOT="/Users/drujensen/.swiftenv"
export PATH="$SWIFTENV_ROOT/bin:$PATH"
eval "$(swiftenv init -)"

#mojo
export MODULAR_HOME="/Users/drujensen/.modular"
export PATH="/Users/drujensen/.modular/pkg/packages.modular.com_mojo/bin:$PATH"

# crystal
export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/opt/openssl/lib"

# rust environment
. "$HOME/.cargo/env"

# java
export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/opt/libsodium/lib"
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# dotnet
export DOTNET_ROOT="$HOME/.dotnet"
export DOTNET_TOOLS="$HOME/.dotnet/tools"
export PATH="$DOTNET_ROOT:$DOTNET_TOOLS:$PATH"

# pipx
export PATH="$PATH:/Users/drujensen/.local/bin"


# bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

# bash-git-prompt
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  GIT_PROMPT_ONLY_IN_REPO=1
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi

# git completion hack
if [ -f `brew --prefix`/etc/bash_completion.d/git-completion.bash ]; then
  . `brew --prefix`/etc/bash_completion.d/git-completion.bash
fi

# alias's
alias gbr='git checkout master; git fetch --all --prune ; git pull origin master; git branch | grep -v "master" | xargs git branch -D'
alias gbm='git checkout main; git fetch --all --prune; git pull origin main; git branch | grep -v "main" | xargs git branch -D'
alias gbt='git checkout trunk; git fetch --all --prune; git pull origin trunk; git branch | grep -v "trunk" | xargs git branch -D'
alias vi='$(brew --prefix)/bin/vim'
alias be='bundle exec'
alias d="docker"
alias dc="docker compose"
alias dp="docker system prune -f --volumes"
alias dl="aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 630519457484.dkr.ecr.us-west-2.amazonaws.com"
alias brewski='brew update && brew upgrade && brew cleanup; brew doctor'
alias xcode='xed'

# prompt
PS1="\[\033[1;36m\]\u\[\033[32m\]\[\\033[0m\]:\[\033[32m\]\w\[\033[0m\]\n$"
